// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GDProtocol
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GD.Protocol {

  /// <summary>Holder for reflection information generated from GDProtocol</summary>
  public static partial class GDProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for GDProtocol</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GDProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpHRFByb3RvY29sEgtHRC5wcm90b2NvbCI6CghWb2x1bnRhchIKCgJpZBgB",
            "IAEoCRIQCgh1c2VybmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCSJECgdE",
            "b25hdG9yEgoKAmlkGAEgASgJEgwKBG51bWUYAiABKAkSDgoGYWRyZXNhGAMg",
            "ASgJEg8KB3RlbGVmb24YBCABKAkiKQoKRG9uYXRpaURUTxINCgVudW1lQxgB",
            "IAEoCRIMCgRzdW1hGAIgASgCIkcKB0RvbmF0aWUSCgoCaWQYASABKAkSDwoH",
            "Y2F1emFJZBgCIAEoCRIRCglkb25hdG9ySWQYAyABKAkSDAoEc3VtYRgEIAEo",
            "CSJCCgVDYXV6YRIKCgJpZBgBIAEoCRIMCgRudW1lGAIgASgJEhEKCWRlc2Ny",
            "aWVyZRgDIAEoCRIMCgRzdW1hGAQgASgJIu8CCglHRFJlcXVlc3QSKQoEdHlw",
            "ZRgBIAEoDjIbLkdELnByb3RvY29sLkdEUmVxdWVzdC5UeXBlEiUKBHVzZXIY",
            "AiABKAsyFS5HRC5wcm90b2NvbC5Wb2x1bnRhckgAEicKB2RvbmF0b3IYAyAB",
            "KAsyFC5HRC5wcm90b2NvbC5Eb25hdG9ySAASJwoHZG9uYXRpZRgEIAEoCzIU",
            "LkdELnByb3RvY29sLkRvbmF0aWVIABIjCgVjYXV6YRgFIAEoCzISLkdELnBy",
            "b3RvY29sLkNhdXphSAAijQEKBFR5cGUSCgoGVW5rb3duEAASCQoFTG9naW4Q",
            "ARIKCgZMb2dvdXQQAhIQCgxHZXREb25hdGlvbnMQAxIPCgtHZXREb25hdG9y",
            "cxAEEg4KCk5ld0RvbmF0b3IQBRIPCgtOZXdEb25hdGlvbhAGEg8KC0ZpbmRE",
            "b25hdG9yEAcSDQoJRmluZENhdXphEAhCCQoHcGF5bG9hZCKLBAoKR0RSZXNw",
            "b25zZRIqCgR0eXBlGAEgASgOMhwuR0QucHJvdG9jb2wuR0RSZXNwb25zZS5U",
            "eXBlEg0KBWVycm9yGAIgASgJEiYKCGRvbmF0b3JzGAMgAygLMhQuR0QucHJv",
            "dG9jb2wuRG9uYXRvchIjCgR1c2VyGAQgASgLMhUuR0QucHJvdG9jb2wuVm9s",
            "dW50YXISJwoJZG9uYXRpb25zGAUgAygLMhQuR0QucHJvdG9jb2wuRG9uYXRp",
            "ZRIhCgVjYXV6ZRgGIAMoCzISLkdELnByb3RvY29sLkNhdXphEiUKB2RvbmF0",
            "b3IYByABKAsyFC5HRC5wcm90b2NvbC5Eb25hdG9yEiEKBWNhdXphGAggASgL",
            "MhIuR0QucHJvdG9jb2wuQ2F1emESJQoHZG9uYXRpZRgJIAEoCzIULkdELnBy",
            "b3RvY29sLkRvbmF0aWUSKwoKZG9uYXRpaURUTxgKIAMoCzIXLkdELnByb3Rv",
            "Y29sLkRvbmF0aWlEVE8iigEKBFR5cGUSCwoHVW5rbm93bhAAEgYKAk9rEAES",
            "CQoFRXJyb3IQAhIQCgxHZXREb25hdGlvbnMQAxIOCgpOZXdEb25hdG9yEAQS",
            "DwoLTmV3RG9uYXRpb24QBRIPCgtHZXREb25hdG9ycxAGEg8KC0ZpbmREb25h",
            "dG9yEAcSDQoJRmluZENhdXphEAhCNgoncm8ubXBwMjAyNC5uZXR3b3JraW5n",
            "LnByb3RvYnVmZnByb3RvY29sQgtHRFByb3RvYnVmc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GD.Protocol.Voluntar), global::GD.Protocol.Voluntar.Parser, new[]{ "Id", "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GD.Protocol.Donator), global::GD.Protocol.Donator.Parser, new[]{ "Id", "Nume", "Adresa", "Telefon" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GD.Protocol.DonatiiDTO), global::GD.Protocol.DonatiiDTO.Parser, new[]{ "NumeC", "Suma" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GD.Protocol.Donatie), global::GD.Protocol.Donatie.Parser, new[]{ "Id", "CauzaId", "DonatorId", "Suma" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GD.Protocol.Cauza), global::GD.Protocol.Cauza.Parser, new[]{ "Id", "Nume", "Descriere", "Suma" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GD.Protocol.GDRequest), global::GD.Protocol.GDRequest.Parser, new[]{ "Type", "User", "Donator", "Donatie", "Cauza" }, new[]{ "Payload" }, new[]{ typeof(global::GD.Protocol.GDRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GD.Protocol.GDResponse), global::GD.Protocol.GDResponse.Parser, new[]{ "Type", "Error", "Donators", "User", "Donations", "Cauze", "Donator", "Cauza", "Donatie", "DonatiiDTO" }, null, new[]{ typeof(global::GD.Protocol.GDResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Voluntar : pb::IMessage<Voluntar>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Voluntar> _parser = new pb::MessageParser<Voluntar>(() => new Voluntar());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Voluntar> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GD.Protocol.GDProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Voluntar() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Voluntar(Voluntar other) : this() {
      id_ = other.id_;
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Voluntar Clone() {
      return new Voluntar(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Voluntar);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Voluntar other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Voluntar other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Donator : pb::IMessage<Donator>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Donator> _parser = new pb::MessageParser<Donator>(() => new Donator());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Donator> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GD.Protocol.GDProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Donator() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Donator(Donator other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      adresa_ = other.adresa_;
      telefon_ = other.telefon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Donator Clone() {
      return new Donator(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "adresa" field.</summary>
    public const int AdresaFieldNumber = 3;
    private string adresa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Adresa {
      get { return adresa_; }
      set {
        adresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "telefon" field.</summary>
    public const int TelefonFieldNumber = 4;
    private string telefon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Telefon {
      get { return telefon_; }
      set {
        telefon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Donator);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Donator other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (Adresa != other.Adresa) return false;
      if (Telefon != other.Telefon) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Adresa.Length != 0) hash ^= Adresa.GetHashCode();
      if (Telefon.Length != 0) hash ^= Telefon.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Adresa.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Adresa);
      }
      if (Telefon.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Telefon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Adresa.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Adresa);
      }
      if (Telefon.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Telefon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Adresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Adresa);
      }
      if (Telefon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Telefon);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Donator other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Adresa.Length != 0) {
        Adresa = other.Adresa;
      }
      if (other.Telefon.Length != 0) {
        Telefon = other.Telefon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Adresa = input.ReadString();
            break;
          }
          case 34: {
            Telefon = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Adresa = input.ReadString();
            break;
          }
          case 34: {
            Telefon = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DonatiiDTO : pb::IMessage<DonatiiDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DonatiiDTO> _parser = new pb::MessageParser<DonatiiDTO>(() => new DonatiiDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DonatiiDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GD.Protocol.GDProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DonatiiDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DonatiiDTO(DonatiiDTO other) : this() {
      numeC_ = other.numeC_;
      suma_ = other.suma_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DonatiiDTO Clone() {
      return new DonatiiDTO(this);
    }

    /// <summary>Field number for the "numeC" field.</summary>
    public const int NumeCFieldNumber = 1;
    private string numeC_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeC {
      get { return numeC_; }
      set {
        numeC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "suma" field.</summary>
    public const int SumaFieldNumber = 2;
    private float suma_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Suma {
      get { return suma_; }
      set {
        suma_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DonatiiDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DonatiiDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumeC != other.NumeC) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Suma, other.Suma)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NumeC.Length != 0) hash ^= NumeC.GetHashCode();
      if (Suma != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Suma);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NumeC.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NumeC);
      }
      if (Suma != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Suma);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NumeC.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NumeC);
      }
      if (Suma != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Suma);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NumeC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeC);
      }
      if (Suma != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DonatiiDTO other) {
      if (other == null) {
        return;
      }
      if (other.NumeC.Length != 0) {
        NumeC = other.NumeC;
      }
      if (other.Suma != 0F) {
        Suma = other.Suma;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            NumeC = input.ReadString();
            break;
          }
          case 21: {
            Suma = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            NumeC = input.ReadString();
            break;
          }
          case 21: {
            Suma = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Donatie : pb::IMessage<Donatie>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Donatie> _parser = new pb::MessageParser<Donatie>(() => new Donatie());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Donatie> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GD.Protocol.GDProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Donatie() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Donatie(Donatie other) : this() {
      id_ = other.id_;
      cauzaId_ = other.cauzaId_;
      donatorId_ = other.donatorId_;
      suma_ = other.suma_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Donatie Clone() {
      return new Donatie(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cauzaId" field.</summary>
    public const int CauzaIdFieldNumber = 2;
    private string cauzaId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CauzaId {
      get { return cauzaId_; }
      set {
        cauzaId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "donatorId" field.</summary>
    public const int DonatorIdFieldNumber = 3;
    private string donatorId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DonatorId {
      get { return donatorId_; }
      set {
        donatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "suma" field.</summary>
    public const int SumaFieldNumber = 4;
    private string suma_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Suma {
      get { return suma_; }
      set {
        suma_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Donatie);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Donatie other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (CauzaId != other.CauzaId) return false;
      if (DonatorId != other.DonatorId) return false;
      if (Suma != other.Suma) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (CauzaId.Length != 0) hash ^= CauzaId.GetHashCode();
      if (DonatorId.Length != 0) hash ^= DonatorId.GetHashCode();
      if (Suma.Length != 0) hash ^= Suma.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (CauzaId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CauzaId);
      }
      if (DonatorId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DonatorId);
      }
      if (Suma.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Suma);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (CauzaId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CauzaId);
      }
      if (DonatorId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DonatorId);
      }
      if (Suma.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Suma);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (CauzaId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CauzaId);
      }
      if (DonatorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DonatorId);
      }
      if (Suma.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Suma);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Donatie other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.CauzaId.Length != 0) {
        CauzaId = other.CauzaId;
      }
      if (other.DonatorId.Length != 0) {
        DonatorId = other.DonatorId;
      }
      if (other.Suma.Length != 0) {
        Suma = other.Suma;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            CauzaId = input.ReadString();
            break;
          }
          case 26: {
            DonatorId = input.ReadString();
            break;
          }
          case 34: {
            Suma = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            CauzaId = input.ReadString();
            break;
          }
          case 26: {
            DonatorId = input.ReadString();
            break;
          }
          case 34: {
            Suma = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Cauza : pb::IMessage<Cauza>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Cauza> _parser = new pb::MessageParser<Cauza>(() => new Cauza());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Cauza> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GD.Protocol.GDProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cauza() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cauza(Cauza other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      descriere_ = other.descriere_;
      suma_ = other.suma_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cauza Clone() {
      return new Cauza(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "descriere" field.</summary>
    public const int DescriereFieldNumber = 3;
    private string descriere_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Descriere {
      get { return descriere_; }
      set {
        descriere_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "suma" field.</summary>
    public const int SumaFieldNumber = 4;
    private string suma_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Suma {
      get { return suma_; }
      set {
        suma_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Cauza);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Cauza other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (Descriere != other.Descriere) return false;
      if (Suma != other.Suma) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Descriere.Length != 0) hash ^= Descriere.GetHashCode();
      if (Suma.Length != 0) hash ^= Suma.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Descriere.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Descriere);
      }
      if (Suma.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Suma);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Descriere.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Descriere);
      }
      if (Suma.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Suma);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Descriere.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Descriere);
      }
      if (Suma.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Suma);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Cauza other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Descriere.Length != 0) {
        Descriere = other.Descriere;
      }
      if (other.Suma.Length != 0) {
        Suma = other.Suma;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Descriere = input.ReadString();
            break;
          }
          case 34: {
            Suma = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Descriere = input.ReadString();
            break;
          }
          case 34: {
            Suma = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GDRequest : pb::IMessage<GDRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GDRequest> _parser = new pb::MessageParser<GDRequest>(() => new GDRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GDRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GD.Protocol.GDProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GDRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GDRequest(GDRequest other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.User:
          User = other.User.Clone();
          break;
        case PayloadOneofCase.Donator:
          Donator = other.Donator.Clone();
          break;
        case PayloadOneofCase.Donatie:
          Donatie = other.Donatie.Clone();
          break;
        case PayloadOneofCase.Cauza:
          Cauza = other.Cauza.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GDRequest Clone() {
      return new GDRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::GD.Protocol.GDRequest.Types.Type type_ = global::GD.Protocol.GDRequest.Types.Type.Unkown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.GDRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.Voluntar User {
      get { return payloadCase_ == PayloadOneofCase.User ? (global::GD.Protocol.Voluntar) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.User;
      }
    }

    /// <summary>Field number for the "donator" field.</summary>
    public const int DonatorFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.Donator Donator {
      get { return payloadCase_ == PayloadOneofCase.Donator ? (global::GD.Protocol.Donator) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Donator;
      }
    }

    /// <summary>Field number for the "donatie" field.</summary>
    public const int DonatieFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.Donatie Donatie {
      get { return payloadCase_ == PayloadOneofCase.Donatie ? (global::GD.Protocol.Donatie) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Donatie;
      }
    }

    /// <summary>Field number for the "cauza" field.</summary>
    public const int CauzaFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.Cauza Cauza {
      get { return payloadCase_ == PayloadOneofCase.Cauza ? (global::GD.Protocol.Cauza) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Cauza;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      User = 2,
      Donator = 3,
      Donatie = 4,
      Cauza = 5,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GDRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GDRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(User, other.User)) return false;
      if (!object.Equals(Donator, other.Donator)) return false;
      if (!object.Equals(Donatie, other.Donatie)) return false;
      if (!object.Equals(Cauza, other.Cauza)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::GD.Protocol.GDRequest.Types.Type.Unkown) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.User) hash ^= User.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Donator) hash ^= Donator.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Donatie) hash ^= Donatie.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Cauza) hash ^= Cauza.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::GD.Protocol.GDRequest.Types.Type.Unkown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (payloadCase_ == PayloadOneofCase.Donator) {
        output.WriteRawTag(26);
        output.WriteMessage(Donator);
      }
      if (payloadCase_ == PayloadOneofCase.Donatie) {
        output.WriteRawTag(34);
        output.WriteMessage(Donatie);
      }
      if (payloadCase_ == PayloadOneofCase.Cauza) {
        output.WriteRawTag(42);
        output.WriteMessage(Cauza);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::GD.Protocol.GDRequest.Types.Type.Unkown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (payloadCase_ == PayloadOneofCase.Donator) {
        output.WriteRawTag(26);
        output.WriteMessage(Donator);
      }
      if (payloadCase_ == PayloadOneofCase.Donatie) {
        output.WriteRawTag(34);
        output.WriteMessage(Donatie);
      }
      if (payloadCase_ == PayloadOneofCase.Cauza) {
        output.WriteRawTag(42);
        output.WriteMessage(Cauza);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::GD.Protocol.GDRequest.Types.Type.Unkown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (payloadCase_ == PayloadOneofCase.Donator) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Donator);
      }
      if (payloadCase_ == PayloadOneofCase.Donatie) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Donatie);
      }
      if (payloadCase_ == PayloadOneofCase.Cauza) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cauza);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GDRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::GD.Protocol.GDRequest.Types.Type.Unkown) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.User:
          if (User == null) {
            User = new global::GD.Protocol.Voluntar();
          }
          User.MergeFrom(other.User);
          break;
        case PayloadOneofCase.Donator:
          if (Donator == null) {
            Donator = new global::GD.Protocol.Donator();
          }
          Donator.MergeFrom(other.Donator);
          break;
        case PayloadOneofCase.Donatie:
          if (Donatie == null) {
            Donatie = new global::GD.Protocol.Donatie();
          }
          Donatie.MergeFrom(other.Donatie);
          break;
        case PayloadOneofCase.Cauza:
          if (Cauza == null) {
            Cauza = new global::GD.Protocol.Cauza();
          }
          Cauza.MergeFrom(other.Cauza);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::GD.Protocol.GDRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::GD.Protocol.Voluntar subBuilder = new global::GD.Protocol.Voluntar();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 26: {
            global::GD.Protocol.Donator subBuilder = new global::GD.Protocol.Donator();
            if (payloadCase_ == PayloadOneofCase.Donator) {
              subBuilder.MergeFrom(Donator);
            }
            input.ReadMessage(subBuilder);
            Donator = subBuilder;
            break;
          }
          case 34: {
            global::GD.Protocol.Donatie subBuilder = new global::GD.Protocol.Donatie();
            if (payloadCase_ == PayloadOneofCase.Donatie) {
              subBuilder.MergeFrom(Donatie);
            }
            input.ReadMessage(subBuilder);
            Donatie = subBuilder;
            break;
          }
          case 42: {
            global::GD.Protocol.Cauza subBuilder = new global::GD.Protocol.Cauza();
            if (payloadCase_ == PayloadOneofCase.Cauza) {
              subBuilder.MergeFrom(Cauza);
            }
            input.ReadMessage(subBuilder);
            Cauza = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::GD.Protocol.GDRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::GD.Protocol.Voluntar subBuilder = new global::GD.Protocol.Voluntar();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 26: {
            global::GD.Protocol.Donator subBuilder = new global::GD.Protocol.Donator();
            if (payloadCase_ == PayloadOneofCase.Donator) {
              subBuilder.MergeFrom(Donator);
            }
            input.ReadMessage(subBuilder);
            Donator = subBuilder;
            break;
          }
          case 34: {
            global::GD.Protocol.Donatie subBuilder = new global::GD.Protocol.Donatie();
            if (payloadCase_ == PayloadOneofCase.Donatie) {
              subBuilder.MergeFrom(Donatie);
            }
            input.ReadMessage(subBuilder);
            Donatie = subBuilder;
            break;
          }
          case 42: {
            global::GD.Protocol.Cauza subBuilder = new global::GD.Protocol.Cauza();
            if (payloadCase_ == PayloadOneofCase.Cauza) {
              subBuilder.MergeFrom(Cauza);
            }
            input.ReadMessage(subBuilder);
            Cauza = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GDRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unkown")] Unkown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("GetDonations")] GetDonations = 3,
        [pbr::OriginalName("GetDonators")] GetDonators = 4,
        [pbr::OriginalName("NewDonator")] NewDonator = 5,
        [pbr::OriginalName("NewDonation")] NewDonation = 6,
        [pbr::OriginalName("FindDonator")] FindDonator = 7,
        [pbr::OriginalName("FindCauza")] FindCauza = 8,
      }

    }
    #endregion

  }

  public sealed partial class GDResponse : pb::IMessage<GDResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GDResponse> _parser = new pb::MessageParser<GDResponse>(() => new GDResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GDResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GD.Protocol.GDProtocolReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GDResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GDResponse(GDResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      donators_ = other.donators_.Clone();
      user_ = other.user_ != null ? other.user_.Clone() : null;
      donations_ = other.donations_.Clone();
      cauze_ = other.cauze_.Clone();
      donator_ = other.donator_ != null ? other.donator_.Clone() : null;
      cauza_ = other.cauza_ != null ? other.cauza_.Clone() : null;
      donatie_ = other.donatie_ != null ? other.donatie_.Clone() : null;
      donatiiDTO_ = other.donatiiDTO_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GDResponse Clone() {
      return new GDResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::GD.Protocol.GDResponse.Types.Type type_ = global::GD.Protocol.GDResponse.Types.Type.Unknown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.GDResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    /// <summary>
    /// One of the following will be filled in, depending on the type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "donators" field.</summary>
    public const int DonatorsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::GD.Protocol.Donator> _repeated_donators_codec
        = pb::FieldCodec.ForMessage(26, global::GD.Protocol.Donator.Parser);
    private readonly pbc::RepeatedField<global::GD.Protocol.Donator> donators_ = new pbc::RepeatedField<global::GD.Protocol.Donator>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GD.Protocol.Donator> Donators {
      get { return donators_; }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 4;
    private global::GD.Protocol.Voluntar user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.Voluntar User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    /// <summary>Field number for the "donations" field.</summary>
    public const int DonationsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::GD.Protocol.Donatie> _repeated_donations_codec
        = pb::FieldCodec.ForMessage(42, global::GD.Protocol.Donatie.Parser);
    private readonly pbc::RepeatedField<global::GD.Protocol.Donatie> donations_ = new pbc::RepeatedField<global::GD.Protocol.Donatie>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GD.Protocol.Donatie> Donations {
      get { return donations_; }
    }

    /// <summary>Field number for the "cauze" field.</summary>
    public const int CauzeFieldNumber = 6;
    private static readonly pb::FieldCodec<global::GD.Protocol.Cauza> _repeated_cauze_codec
        = pb::FieldCodec.ForMessage(50, global::GD.Protocol.Cauza.Parser);
    private readonly pbc::RepeatedField<global::GD.Protocol.Cauza> cauze_ = new pbc::RepeatedField<global::GD.Protocol.Cauza>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GD.Protocol.Cauza> Cauze {
      get { return cauze_; }
    }

    /// <summary>Field number for the "donator" field.</summary>
    public const int DonatorFieldNumber = 7;
    private global::GD.Protocol.Donator donator_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.Donator Donator {
      get { return donator_; }
      set {
        donator_ = value;
      }
    }

    /// <summary>Field number for the "cauza" field.</summary>
    public const int CauzaFieldNumber = 8;
    private global::GD.Protocol.Cauza cauza_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.Cauza Cauza {
      get { return cauza_; }
      set {
        cauza_ = value;
      }
    }

    /// <summary>Field number for the "donatie" field.</summary>
    public const int DonatieFieldNumber = 9;
    private global::GD.Protocol.Donatie donatie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GD.Protocol.Donatie Donatie {
      get { return donatie_; }
      set {
        donatie_ = value;
      }
    }

    /// <summary>Field number for the "donatiiDTO" field.</summary>
    public const int DonatiiDTOFieldNumber = 10;
    private static readonly pb::FieldCodec<global::GD.Protocol.DonatiiDTO> _repeated_donatiiDTO_codec
        = pb::FieldCodec.ForMessage(82, global::GD.Protocol.DonatiiDTO.Parser);
    private readonly pbc::RepeatedField<global::GD.Protocol.DonatiiDTO> donatiiDTO_ = new pbc::RepeatedField<global::GD.Protocol.DonatiiDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::GD.Protocol.DonatiiDTO> DonatiiDTO {
      get { return donatiiDTO_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GDResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GDResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if(!donators_.Equals(other.donators_)) return false;
      if (!object.Equals(User, other.User)) return false;
      if(!donations_.Equals(other.donations_)) return false;
      if(!cauze_.Equals(other.cauze_)) return false;
      if (!object.Equals(Donator, other.Donator)) return false;
      if (!object.Equals(Cauza, other.Cauza)) return false;
      if (!object.Equals(Donatie, other.Donatie)) return false;
      if(!donatiiDTO_.Equals(other.donatiiDTO_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::GD.Protocol.GDResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= donators_.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      hash ^= donations_.GetHashCode();
      hash ^= cauze_.GetHashCode();
      if (donator_ != null) hash ^= Donator.GetHashCode();
      if (cauza_ != null) hash ^= Cauza.GetHashCode();
      if (donatie_ != null) hash ^= Donatie.GetHashCode();
      hash ^= donatiiDTO_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::GD.Protocol.GDResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      donators_.WriteTo(output, _repeated_donators_codec);
      if (user_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(User);
      }
      donations_.WriteTo(output, _repeated_donations_codec);
      cauze_.WriteTo(output, _repeated_cauze_codec);
      if (donator_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Donator);
      }
      if (cauza_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Cauza);
      }
      if (donatie_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Donatie);
      }
      donatiiDTO_.WriteTo(output, _repeated_donatiiDTO_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::GD.Protocol.GDResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      donators_.WriteTo(ref output, _repeated_donators_codec);
      if (user_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(User);
      }
      donations_.WriteTo(ref output, _repeated_donations_codec);
      cauze_.WriteTo(ref output, _repeated_cauze_codec);
      if (donator_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Donator);
      }
      if (cauza_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Cauza);
      }
      if (donatie_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Donatie);
      }
      donatiiDTO_.WriteTo(ref output, _repeated_donatiiDTO_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::GD.Protocol.GDResponse.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      size += donators_.CalculateSize(_repeated_donators_codec);
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      size += donations_.CalculateSize(_repeated_donations_codec);
      size += cauze_.CalculateSize(_repeated_cauze_codec);
      if (donator_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Donator);
      }
      if (cauza_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cauza);
      }
      if (donatie_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Donatie);
      }
      size += donatiiDTO_.CalculateSize(_repeated_donatiiDTO_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GDResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::GD.Protocol.GDResponse.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      donators_.Add(other.donators_);
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::GD.Protocol.Voluntar();
        }
        User.MergeFrom(other.User);
      }
      donations_.Add(other.donations_);
      cauze_.Add(other.cauze_);
      if (other.donator_ != null) {
        if (donator_ == null) {
          Donator = new global::GD.Protocol.Donator();
        }
        Donator.MergeFrom(other.Donator);
      }
      if (other.cauza_ != null) {
        if (cauza_ == null) {
          Cauza = new global::GD.Protocol.Cauza();
        }
        Cauza.MergeFrom(other.Cauza);
      }
      if (other.donatie_ != null) {
        if (donatie_ == null) {
          Donatie = new global::GD.Protocol.Donatie();
        }
        Donatie.MergeFrom(other.Donatie);
      }
      donatiiDTO_.Add(other.donatiiDTO_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::GD.Protocol.GDResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            donators_.AddEntriesFrom(input, _repeated_donators_codec);
            break;
          }
          case 34: {
            if (user_ == null) {
              User = new global::GD.Protocol.Voluntar();
            }
            input.ReadMessage(User);
            break;
          }
          case 42: {
            donations_.AddEntriesFrom(input, _repeated_donations_codec);
            break;
          }
          case 50: {
            cauze_.AddEntriesFrom(input, _repeated_cauze_codec);
            break;
          }
          case 58: {
            if (donator_ == null) {
              Donator = new global::GD.Protocol.Donator();
            }
            input.ReadMessage(Donator);
            break;
          }
          case 66: {
            if (cauza_ == null) {
              Cauza = new global::GD.Protocol.Cauza();
            }
            input.ReadMessage(Cauza);
            break;
          }
          case 74: {
            if (donatie_ == null) {
              Donatie = new global::GD.Protocol.Donatie();
            }
            input.ReadMessage(Donatie);
            break;
          }
          case 82: {
            donatiiDTO_.AddEntriesFrom(input, _repeated_donatiiDTO_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::GD.Protocol.GDResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            donators_.AddEntriesFrom(ref input, _repeated_donators_codec);
            break;
          }
          case 34: {
            if (user_ == null) {
              User = new global::GD.Protocol.Voluntar();
            }
            input.ReadMessage(User);
            break;
          }
          case 42: {
            donations_.AddEntriesFrom(ref input, _repeated_donations_codec);
            break;
          }
          case 50: {
            cauze_.AddEntriesFrom(ref input, _repeated_cauze_codec);
            break;
          }
          case 58: {
            if (donator_ == null) {
              Donator = new global::GD.Protocol.Donator();
            }
            input.ReadMessage(Donator);
            break;
          }
          case 66: {
            if (cauza_ == null) {
              Cauza = new global::GD.Protocol.Cauza();
            }
            input.ReadMessage(Cauza);
            break;
          }
          case 74: {
            if (donatie_ == null) {
              Donatie = new global::GD.Protocol.Donatie();
            }
            input.ReadMessage(Donatie);
            break;
          }
          case 82: {
            donatiiDTO_.AddEntriesFrom(ref input, _repeated_donatiiDTO_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GDResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("GetDonations")] GetDonations = 3,
        [pbr::OriginalName("NewDonator")] NewDonator = 4,
        [pbr::OriginalName("NewDonation")] NewDonation = 5,
        [pbr::OriginalName("GetDonators")] GetDonators = 6,
        [pbr::OriginalName("FindDonator")] FindDonator = 7,
        [pbr::OriginalName("FindCauza")] FindCauza = 8,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
